apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service 
spec:
  selector:
    matchLabels:
      run: upload-service
  replicas: 1
  template:
    metadata:
      labels:
        run: upload-service
    spec:
      containers:
      - name: upload-service
        image: github.com/coffeemakingtoaster/water-bottler/upload-service:local
        ports:
        - containerPort: 8081
        env:
        - name: AUTH_SERVICE_URL
          value: "http://authentication-service.default.svc.cluster.local:8080"
        - name: QUEUE_URL
          value: "amqp://water:bottler@dev-cluster.default.svc.cluster.local:5672"
        - name: MINIO_ACCESS_KEY
          value: water
        - name: MINIO_SECRET_KEY
          value: bottler123
        - name: MINIO_ENDPOINT
          value: "minio-service.default.svc.cluster.local:9000"
        - name: MINIO_BUCKET_NAME
          value: water-buckid

---

apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    run: upload-service 
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
    nodePort: 30081 
  selector:
    run: upload-service
