apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service 
spec:
  selector:
    matchLabels:
      run: upload-service
  replicas: 1
  template:
    metadata:
      labels:
        run: upload-service
    spec:
      containers:
      - name: upload-service
        image: github.com/coffeemakingtoaster/water-bottler/upload-service:local
        ports:
        - containerPort: 8081
        env:
        - name: AUTH_SERVICE_URL
          value: "authentication-service.default.svc.cluster.local:8080"
        - name: QUEUE_URL
          value: "amqp://water:bottler@dev-cluster.default.svc.cluster.local:5672"

---

apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    run: upload-service 
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
  selector:
    run: upload-service

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice-expose
spec:
  ingressClassName: nginx 
  rules:
    - host: water-bottler.local
      http:
        paths:
          - path: /upload-service
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: 8080
