apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        ports:
        - containerPort: 9000
        - containerPort: 9090
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.accessKey }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.minio.accessKeySecret }}
        volumeMounts:
        - mountPath: /data
          name:  storage 
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    name: api
    protocol: TCP
  - port: 9090
    name: web-interface
    protocol: TCP
  selector:
    app: minio


