apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: {{ .Release.Namespace }}
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
    ports:
    - containerPort: 9000
    - containerPort: 9090
    env:
    # Note: This obv is not ideal for a production environment
    - name: MINIO_ROOT_USER
      value: {{ .Values.minio.accessKey }}
    - name: MINIO_ROOT_PASSWORD
      value: {{ .Values.minio.accessKeySecret }}
      #volumeMounts:
        #- mountPath: /data
      #name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
  #volumes:
  #- name: localvolume
    #hostPath: # MinIO generally recommends using locally-attached volumes
      #path: /mnt/disk1/data # Specify a path to a local drive or volume on the Kubernetes worker node
      #type: DirectoryOrCreate # The path to the last directory must exist
---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    name: api
    protocol: TCP
  - port: 9090
    name: web-interface
    protocol: TCP
  selector:
    app: minio


