apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-recognition-service
spec:
  selector:
    matchLabels:
      run: object-recognition-service
  template:
    metadata:
      labels:
        run: object-recognition-service
    spec:
      containers:
      - name: object-recognition-service
        image: ghcr.io/coffeemakingtoaster/water-bottler/object-recognition-service:{{ .Values.globalImageTag }}
        env: 
        - name: QUEUE_HOST
          value: {{ tpl $.Values.objectRecognitionService.configuration.queueHost $ }}
        - name: QUEUE_USER
          value: {{ .Values.rabbitmq.username }}
        - name: QUEUE_PASS
          value: {{ .Values.rabbitmq.password }}
        - name: MINIO_USER
          value: {{ .Values.minio.accessKey }}
        - name: MINIO_KEY
          value: {{ .Values.minio.accessKeySecret }}
        - name: MINIO_ENDPOINT
          value: {{ tpl $.Values.uploadService.configuration.minioEndpoint $ }}
        - name: MINIO_BUCKET
          value: {{ .Values.minio.bucketName }}
        - name: QUEUE_INPUT_NAME
          value: "image-workload"
        - name: QUEUE_OUTPUT_NAME
          value: "finished-jobs"
        - name: SLOW_MODE_DELAY
          value: {{ quote .Values.objectRecognitionService.configuration.delay }}

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: object-recognition-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: object-recognition-service
  minReplicas: {{ .Values.objectRecognitionService.scaling.minInstances }}
  maxReplicas: {{ .Values.objectRecognitionService.scaling.maxInstances }}
  metrics:
  - type: Object
    object:
      metric: 
        name: rabbitmq_queue_messages_unacked
      describedObject:
        apiVersion: v1
        kind: Service
        # point to rabbitmq service
        name: water-bottler-cluster
      target:
        type: Value
        value: {{ .Values.objectRecognitionService.scaling.scalingMetricThreshhold }}
