apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: water-bottler-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  override:
    service:
        metadata:
          labels:
            release: prometheus-stack
  rabbitmq:
    additionalConfig: |
      default_user={{ .Values.rabbitmq.username }}
      default_pass={{ .Values.rabbitmq.password }}

--- 

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  labels:
    # This (obviously) is implied. I still leave it here to warn anyone: Remove this and autoscaling breaks
    release: {{ .Release.Name }}
spec:
  endpoints:
  - port: prometheus
    scheme: http
    interval: 15s
    scrapeTimeout: 14s
  - port: prometheus-tls
    scheme: https
    interval: 15s
    scrapeTimeout: 14s
    tlsConfig:
      insecureSkipVerify: true # set to false and uncomment lines below to enable tls verification
  - port: prometheus
    scheme: http
    path: /metrics/detailed
    params:
      family:
        - queue_coarse_metrics
        - queue_metrics
    interval: 15s
    scrapeTimeout: 14s
  - port: prometheus-tls
    scheme: https
    path: /metrics/detailed
    params:
      family:
        - queue_coarse_metrics
        - queue_metrics
    interval: 15s
    scrapeTimeout: 14s
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true

--- 

# Set adapter to see metric
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    "rules":
    - "seriesQuery": |
         'rabbitmq_queue_messages_unacked{container="rabbitmq"}'
      "resources":
        "template": "<<.Resource>>"
      "name":
        "matches": "^(.*)_unacked"
        "as": "image_queue_workload"
      "metricsQuery": |
          avg_over_time (
            <<.Series>>[1m]
          )

---

# Setup metric publishing to k8s control plane
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: default
  version: v1beta2
  versionPriority: 100
