{{ if .Values.enableSMTPDev }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
  labels:
    app: smtp4dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
      - name: smtp4dev
        image: rnwood/smtp4dev:latest
        ports:
        - containerPort: 80  # webinterface 
        - containerPort: 25  # SMTP port
        env:
        - name: ServerOptions__Urls
          value: "http://*:80"
            #- name: RelayOptions__Login
              #value: "water"
            #- name: RelayOptions__Password
              #value: "bottler"
        - name: ServerOptions__HostName
          value: "water-bottler-mail"

---

apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
  labels:
    app: smtp4dev
spec:
  selector:
    app: smtp4dev
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: smtp
    protocol: TCP
    port: 2525
    targetPort: 25
  type: NodePort

{{ if .Values.enableIngress }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smtp4dev-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: smtp4dev.water-bottler.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smtp4dev
                port:
                  number: 80

{{ end }}

{{ end }}
