apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service 
spec:
  selector:
    matchLabels:
      run: authentication-service
  replicas: 1
  template:
    metadata:
      labels:
        run: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: github.com/coffeemakingtoaster/water-bottler/authentication-service:local
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    run: authentication-service 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: authentication-service
