apiVersion: v1
data:
  db.yaml: |-
    apiKeys:
      - name: "jeff@water-bottler.local"
        key: "amVmZnMtd2F0ZXItYm90dGxlci1leGFtcGxlLWFwaS1rZXk="
        validUntil: "2036-12-31T23:59:59Z"
      - name: "emañuel@water-bottler.local"
        key: "ZW1hw7F1ZWwtd2F0ZXItYm90dGxlci1leGFtcGxlLWFwaS1rZXk="
        validUntil: "1982-01-01T00:00:00Z"
kind: ConfigMap
metadata:
  name: auth-database

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service 
spec:
  selector:
    matchLabels:
      run: authentication-service
  replicas: 1
  template:
    metadata:
      labels:
        run: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: github.com/coffeemakingtoaster/water-bottler/authentication-service:local
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db-config
          mountPath: /app/db.yaml
          subPath: db.yaml                      # Key in the ConfigMap
      volumes:
      - name: db-config 
        configMap:
          name: auth-database

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    run: authentication-service 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: authentication-service


