apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-service 
spec:
  selector:
    matchLabels:
      run: download-service
  replicas: 1
  template:
    metadata:
      labels:
        run: download-service
    spec:
      containers:
      - name: download-service
        image: github.com/coffeemakingtoaster/water-bottler/download-service:local
        ports:
        - containerPort: 8080
        env:
        - name: MINIO_ACCESS_KEY
          value: water
        - name: MINIO_SECRET_KEY
          value: bottler123
        - name: MINIO_ENDPOINT
          value: "minio-service.default.svc.cluster.local:9000"
        - name: MINIO_BUCKET_NAME
          value: water-buckid

---

apiVersion: v1
kind: Service
metadata:
  name: download-service
  labels:
    run: download-service 
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: download-service
