name: GH actions change

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/**/*'
  push:
    branch:
      - 'main'
    paths:
      - '.github/**/*'

jobs:
  test-and-build:
    strategy:
      matrix: 
        dir:
          - authentication-service
          - download-service
          - notification-service
          - upload-service
    uses: ./.github/workflows/go-service.template.yml
    with:
      context: ${{ matrix.dir }}

  docker-build-and-push:
    if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}} # Only run on push to main
    strategy:
      matrix: 
        dir:
          - authentication-service
          - download-service
          - notification-service
          - upload-service
    needs:
      - test-and-build
    uses: ./.github/workflows/docker-build-and-push.template.yml
    with:
      context: ${{ matrix.dir }}

  validate-k8s-definitions:
    strategy:
      matrix: 
        dir:
          - authentication-service
          - download-service
          - notification-service
          - upload-service
          - development-deployments
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.3' 

      - name: install validator
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@latest 

        # Ignore missing because kubeconform cannot validate rabbitmq custom resources
      - name: validation
        run: kubeconform -summary -ignore-missing-schemas ./*.yaml
