name: Go service test,build,docker 

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.context }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.3' 

      - name: build
        run: go build main.go

  test: 
    runs-on: ubuntu-latest
    needs:
      - build
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.context }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.3' 

      - name: test 
        run: go test ./...

