name: go based microservice 

on:
  pull_request:
    branches:
      - main
    paths:
      - helm-chart

  push:
    branches:
      - main
    paths:
      - helm-chart

jobs:
  validate-k8s-definitions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: helm-chart
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4.2.0

      - name: lint chart
        run: helm lint .

